service: next-webpack-plugin

frameworkVersion: "2"
configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: ap-southeast-2

  apiGateway:
    shouldStartNameWithService: true

# layers:
#   baseLayer:
#     path: out_lambda/layer/nodejs
#     name: ${opt:stage, self:provider.stage, 'dev'}-base-layer
#     description: Test Layer
#     compatibleRuntimes:
#       - nodejs12.x
#     licenseInfo: PRIVATE
#     retain: false

# package:
#   exlude: []
#   # exclude:
#   #   - ./**

plugins:
  - serverless-offline

functions:
  index:
    handler: ./out_lambda/lambda/page_index/handler.render
    events:
      - http:
          path: /
          method: ANY

  page1:
    handler: ./out_lambda/lambda/page_page1/handler.render
    events:
      - http:
          path: /
          method: ANY

  page2:
    handler: ./out_lambda/lambda/page_page2/handler.render
    events:
      - http:
          path: /
          method: ANY

  page3:
    handler: ./out_lambda/lambda/page_page3/handler.render
    events:
      - http:
          path: /
          method: ANY

custom:
  serverless-offline:
    noPrependStageInUrl: true
