service: next-serverless-plugin

frameworkVersion: "2"
configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: ap-southeast-2

  apiGateway:
    shouldStartNameWithService: true

plugins:
  - "@sls-next/serverless-plugin"
  # - "@build-tool/next-serverless-plugin"
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
