service: web-demo-app

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "2"
configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: ap-southeast-2

  environment:
    MY_MESSAGE: "Hello World"

  apiGateway:
    shouldStartNameWithService: true

package:
  exclude: []
  include: []

plugins:
  - serverless-offline

functions:
  hello:
    handler: handlers/index.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY

resources:
  Outputs:
    NewOutput:
      Description: "Output description"
      Value: "Example output"
